const ballAnswers = [
  "YEP kok ",
  "Yes. Suske ",
  "Lyuuuuuuuuuuuuuuuuuuu said yes.",
  "bababababa = NODDERS",
  "You may rely on deez nuts NODDERS .",
  "As I see it, yes... Suske ",
  "Most likely. meow",
  "Outlook good. ChadJam ",
  "Yes. Smadge ",
  "Signs point to yes. Smadge ",
  "Ask again later. PogO",
  "Better not tell you now. Plotge ",
  "Cannot predict now. So sorry natsuHehehehehe  ",
  "Ask your father KEKWlaugh ",
  "Ask your mom KEKWlaugh ",
  "Don't count on it. NOPERS ",
  "Outlook not so good. Smadge ",
  "My sources say no. LUBBERS ",
  "Very doubtful.",
  " COPIUM ",
  "I don't know... I only know that WE LOST LYUUUUUUUUUUUUU natsuWhyy natsuCryALot  natsuWhyy natsuCryALot  natsuWhyy natsuCryALot  ",
  "Not everything is certain, but if there's one thing you can count on, it's that C_Killah will always be drunk.",
  "KILLAH STOP ASKING ME QUESTIONS. NATSU HELP! natsuPanic ",
];
